services:
  proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: do_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
    volumes:
      - ./nginx-proxy-manager/config:/config
      - ./nginx-proxy-manager/logs:/var/log/nginx
      - do_proxy_data:/data
      - do_proxy_letsencrypt:/etc/letsencrypt
    depends_on:
      - portainer
      - adminer
    networks:
      - moznet

  portainer:
    image: portainer/portainer-ce
    container_name: do_portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/config:/config
      - ./portainer/logs:/logs
      - do_portainer_data:/data
    networks:
      - moznet

  adminer:
    image: adminer
    container_name: do_adminer
    restart: unless-stopped
    volumes:
      - ./adminer/config:/config
      - ./adminer/logs:/logs
      - do_adminer_data:/var/www/html
    networks:
      - moznet

  # pihole:
  #   image: pihole/pihole:latest
  #   container_name: do_pihole
  #   restart: unless-stopped
  #   ports:
  #     - "5353:53/tcp"
  #     - "5353:53/udp"
  #   environment:
  #     TZ: Asia/Bangkok
  #     WEBPASSWORD: "changeme" # set your admin password
  #   volumes:
  #     - ./pihole/etc-pihole:/etc/pihole
  #     - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
  #   networks:
  #     - moznet

volumes:
  do_proxy_data:
  do_proxy_letsencrypt:
  do_portainer_data:
  do_adminer_data:
  # do_pihole_data:

networks:
  moznet:
    external: true
