#!/bin/sh
set -eu

ROOT_DIR="$(CDPATH='' cd "$(dirname "$0")/.." && pwd)"
TEST_DIR="$(mktemp -d /tmp/dugout-barrel-test.XXXXXX)"

cleanup() {
  rm -r "${TEST_DIR}"
}
trap cleanup 0
trap 'exit 1' 1 2 3 15

help_output="$(cd "${TEST_DIR}" && "${ROOT_DIR}/bin/barrel" --help)"
printf '%s\n' "${help_output}" |
  grep -Fq "Documentation: ${ROOT_DIR}/tools/barrel/barrel.README.md"
printf '%s\n' "${help_output}" |
  grep -Fq "Language definitions: ${ROOT_DIR}/tools/barrel/barrel.languages.yaml"

mkdir -p "${TEST_DIR}/src/models"

cat > "${TEST_DIR}/src/barrel.yaml" <<'EOF'
language: typescript
filename: index
label: "// generated by barrel test"
prefix: "_"
exclude: []
naming:
  2: named
EOF

cat > "${TEST_DIR}/src/app.ts" <<'EOF'
export const app = true;
EOF

cat > "${TEST_DIR}/src/app.spec.ts" <<'EOF'
export const testOnly = true;
EOF

cat > "${TEST_DIR}/src/models/user.ts" <<'EOF'
export interface User { id: string }
EOF

(
  cd "${TEST_DIR}/src"
  "${ROOT_DIR}/bin/barrel" >/dev/null
)

grep -Fqx 'export * from "./app";' "${TEST_DIR}/src/index.ts"
grep -Fqx 'export * from "./models/models";' "${TEST_DIR}/src/index.ts"
grep -Fqx 'export * from "./user";' "${TEST_DIR}/src/models/models.ts"

if grep -Fq 'app.spec' "${TEST_DIR}/src/index.ts"; then
  echo "Barrel did not apply the bundled TypeScript ignore rules." >&2
  exit 1
fi

echo "Dugout Barrel shim, help, and language definitions pass."
