#!/usr/bin/env python3
"""Shared helpers for Dugout's repository-local lifecycle commands."""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parent.parent
STATE_FILE = ROOT / ".dugout-install-state.json"
ENV_FILE = ROOT / ".env"
VERSION = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
COMPOSE_PROJECT = "dugout"
NETWORK = "moznet"

CONTAINERS = (
    "do_portainer",
    "do_adminer",
    "do_mailpit",
    "do_dozzle",
)

VOLUMES = (
    "dugout_do_portainer_data",
    "dugout_do_adminer_data",
    "dugout_do_mailpit_data",
)

SERVICE_IMAGES = (
    "portainer/portainer-ce:2.39.2",
    "adminer:5.4.2",
    "axllent/mailpit:v1.30.6",
    "amir20/dozzle:v10.6.13",
)

TOOL_IMAGES = (
    "moztopia/dugout-php:8.4",
    "moztopia/dugout-composer:2-php84",
    "moztopia/dugout-node:22",
    "moztopia/dugout-npm:10-node22",
    "moztopia/dugout-npx:10-node22",
)

RUNTIME_PATHS = (
    ROOT / "services/portainer/config",
    ROOT / "services/portainer/logs",
    ROOT / "services/adminer/config",
    ROOT / "services/adminer/logs",
)

LEGACY_PROXY_VOLUMES = (
    "dugout_do_proxy_data",
    "dugout_do_proxy_letsencrypt",
    "dugout_do_traefik_letsencrypt",
)

LEGACY_PROXY_CONTAINERS = ("do_proxy",)

LEGACY_PROXY_IMAGES = (
    "jc21/nginx-proxy-manager:2.15.1",
    "traefik:v3.7.1",
)

LEGACY_PROXY_RUNTIME_PATHS = (
    ROOT / "services/nginx-proxy-manager/config",
    ROOT / "services/nginx-proxy-manager/logs",
)

class LifecycleError(RuntimeError):
    """A user-actionable lifecycle failure."""


def run(
    command: list[str],
    *,
    check: bool = True,
    capture: bool = False,
    env: dict[str, str] | None = None,
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        command,
        cwd=ROOT,
        check=check,
        text=True,
        stdout=subprocess.PIPE if capture else None,
        stderr=subprocess.PIPE if capture else None,
        env=env,
    )


def docker_object_exists(arguments: list[str]) -> bool:
    result = run(["docker", *arguments], check=False, capture=True)
    return result.returncode == 0


def image_exists(image: str) -> bool:
    return docker_object_exists(["image", "inspect", image])


def existing_installation_resources() -> list[str]:
    found: list[str] = []
    if STATE_FILE.exists():
        found.append(f"installation state: {STATE_FILE}")
    if ENV_FILE.exists():
        found.append(f"local configuration: {ENV_FILE}")
    for container in CONTAINERS:
        if docker_object_exists(["container", "inspect", container]):
            found.append(f"container: {container}")
    for volume in VOLUMES:
        if docker_object_exists(["volume", "inspect", volume]):
            found.append(f"volume: {volume}")
    if docker_object_exists(["network", "inspect", NETWORK]):
        found.append(f"network: {NETWORK}")
    # Tool images and caches can outlive a checkout (for example, after
    # `docker compose down -v` followed by deleting the repository). They are
    # reusable, non-authoritative data and do not by themselves indicate an
    # existing or partial installation. A recorded installation still owns
    # and removes the ones it created through its state file.
    for path in RUNTIME_PATHS:
        if path.exists() and (not path.is_dir() or any(path.iterdir())):
            found.append(f"runtime data: {path.relative_to(ROOT)}")
    return found


def env_contents(traefik_network_name: str = "web-proxy") -> str:
    return f"""# Generated by make install. This file configures Dugout's local tools.
DUGOUT_IMAGE_PREFIX=moztopia/dugout

DUGOUT_PHP_VERSION=8.4
DUGOUT_COMPOSER_VERSION=2
DUGOUT_NODE_VERSION=22
DUGOUT_NPM_VERSION=10

DUGOUT_PHP_NETWORK=moznet
DUGOUT_COMPOSER_NETWORK=bridge
DUGOUT_NODE_NETWORK=none
DUGOUT_NPM_NETWORK=bridge
DUGOUT_NPX_NETWORK=bridge

# Existing external network shared with the standalone Traefik proxy.
TRAEFIK_NETWORK_NAME={traefik_network_name}
"""


def write_private_file(path: Path, contents: str) -> None:
    descriptor = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
        stream.write(contents)


def cache_paths() -> list[str]:
    cache_root = Path(
        os.environ.get(
            "XDG_CACHE_HOME",
            str(Path.home() / ".cache"),
        )
    ) / "dugout"
    return [
        str(cache_root / "composer-2-php84"),
        str(cache_root / "npm-10-node22"),
    ]


def initial_state(images_to_remove: list[str]) -> dict[str, Any]:
    return {
        "schema": 1,
        "status": "installing",
        "dugout_version": VERSION,
        "compose_project": COMPOSE_PROJECT,
        "network": NETWORK,
        "containers": list(CONTAINERS),
        "volumes": list(VOLUMES),
        "images": images_to_remove,
        "cache_paths": cache_paths(),
        "runtime_paths": [str(path) for path in RUNTIME_PATHS],
        "configuration": str(ENV_FILE),
    }


def write_state(state: dict[str, Any]) -> None:
    temporary = STATE_FILE.with_suffix(".tmp")
    temporary.write_text(
        json.dumps(state, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    temporary.chmod(0o600)
    temporary.replace(STATE_FILE)


def load_state() -> dict[str, Any]:
    try:
        state = json.loads(STATE_FILE.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise LifecycleError(f"Cannot read installation state: {error}") from error
    if state.get("schema") != 1:
        raise LifecycleError("The installation state uses an unsupported schema.")
    allowed = {
        "containers": set((*CONTAINERS, *LEGACY_PROXY_CONTAINERS)),
        "volumes": set((*VOLUMES, *LEGACY_PROXY_VOLUMES)),
        "images": set((*SERVICE_IMAGES, *TOOL_IMAGES, *LEGACY_PROXY_IMAGES)),
        "runtime_paths": {
            str(path) for path in (*RUNTIME_PATHS, *LEGACY_PROXY_RUNTIME_PATHS)
        },
    }
    for key, permitted in allowed.items():
        values = state.get(key)
        if not isinstance(values, list) or not set(values).issubset(permitted):
            raise LifecycleError(
                f"The installation state contains unsafe {key} values."
            )
    if state.get("network") != NETWORK:
        raise LifecycleError("The installation state contains an unsafe network.")
    if state.get("configuration") != str(ENV_FILE):
        raise LifecycleError(
            "The installation state contains an unsafe configuration path."
        )
    return state


def foreign_network_containers() -> list[str]:
    result = run(
        ["docker", "network", "inspect", NETWORK, "--format", "{{json .Containers}}"],
        check=False,
        capture=True,
    )
    if result.returncode != 0:
        return []
    try:
        attached = json.loads(result.stdout.strip() or "{}")
    except json.JSONDecodeError as error:
        raise LifecycleError(
            f"Cannot inspect containers attached to {NETWORK}."
        ) from error
    known = set((*CONTAINERS, *LEGACY_PROXY_CONTAINERS))
    return sorted(
        details.get("Name", identifier)
        for identifier, details in attached.items()
        if details.get("Name", identifier) not in known
    )


def remove_path(path: Path) -> None:
    resolved_root = ROOT.resolve()
    resolved = path.resolve()
    if resolved_root not in resolved.parents:
        raise LifecycleError(f"Refusing to remove path outside Dugout: {resolved}")
    if resolved.is_dir():
        shutil.rmtree(resolved)
    elif resolved.exists():
        resolved.unlink()


def fail(message: str) -> None:
    print(f"\nError: {message}", file=sys.stderr)
    raise SystemExit(1)
